# api测试文件，适用于VSCODE的REST Client

# admin/user
GET http://localhost:3000/api/v1/admin/users HTTP/1.1

POST http://localhost:3000/api/v1/admin/users HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "testpwd",
    "roles": ["admin", "member"]
}

PUT http://localhost:3000/api/v1/admin/users/1 HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "adminpwd",
    "roles": ["admin"]
}

GET http://localhost:3000/api/v1/admin/users/1 HTTP/1.1

DELETE http://localhost:3000/api/v1/admin/users/1 HTTP/1.1

GET http://localhost:3000/api/v1/admin/users/1/roles HTTP/1.1

PUT http://localhost:3000/api/v1/admin/users/1/roles HTTP/1.1
content-type: application/json

{
    "roles": [ "admin" ]
}

# admin/role
GET http://localhost:3000/api/v1/admin/roles HTTP/1.1

POST http://localhost:3000/api/v1/admin/roles HTTP/1.1
content-type: application/json

{
    "name": "admin"
}

PUT http://localhost:3000/api/v1/admin/roles/1 HTTP/1.1
content-type: application/json

{
    "name": "admin"
}

GET http://localhost:3000/api/v1/admin/roles/1 HTTP/1.1

DELETE http://localhost:3000/api/v1/admin/roles/1 HTTP/1.1

GET http://localhost:3000/api/v1/admin/roles/1/permissions HTTP/1.1

PUT http://localhost:3000/api/v1/admin/roles/1/permissions HTTP/1.1
content-type: application/json

{
    "permissions": [ "dashboard" ]
}

# admin/permission
GET http://localhost:3000/api/v1/admin/permissions HTTP/1.1

POST http://localhost:3000/api/v1/admin/permissions HTTP/1.1
content-type: application/json

{
    "name": "admin"
}

PUT http://localhost:3000/api/v1/admin/permissions/1 HTTP/1.1
content-type: application/json

{
    "name": "admin"
}

GET http://localhost:3000/api/v1/admin/permissions/1 HTTP/1.1

DELETE http://localhost:3000/api/v1/admin/permissions/1 HTTP/1.1

# session

GET http://localhost:3000/api/v1/sessions HTTP/1.1

POST http://localhost:3000/api/v1/sessions HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "adminpwd"
}

DELETE http://localhost:3000/api/v1/sessions HTTP/1.1

POST http://localhost:3000/api/v1/sessions/update-password HTTP/1.1
content-type: application/json

{
    "oldPassword": "testpwd",
    "newPassword": "testpwd1",
    "newPasswordRepeat": "testpwd1"
}
